name       : haskell-setenv
version    : 0.1.1.3
release    : 4
source     :
    - http://hackage.haskell.org/package/setenv-0.1.1.3/setenv-0.1.1.3.tar.gz : e358df39afc03d5a39e2ec650652d845c85c80cc98fe331654deafb4767ecb32
license    : MIT
component  : programming.haskell
summary    : A cross-platform library for setting environment variables
description: |
    A cross-platform library for setting environment variables
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
